<template>
  <main id="tapestry" ref="app" :style="{backgroundColor: dragoverBackgroundColor}">
    <div class="slider-instructions" v-if="!empty || tapestryGenerated"> Pull slider to the right to view Tapestry</div>
    <div class="strength-of-relevancy-white-box" v-if="!empty || tapestryGenerated"> 
      <span class="strength-of-relevancy-text">Strength of relevancy connections</span> <br>
      A default connection between nodes is represented in <span class="navy-blue-text">navy blue</span><br>
      The color of the connection represents the <span class="navy-blue-text">strength of the relevancy</span> between grandchild nodes. It represents a correlation number - note that this number is generated by ChatGPT-3.5 after comparing the similarity of texts between two nodes.
    <br>
    <span class="correlation-text">Lower correlation</span> <span class="low-correlation-value-text">70-79</span> <span class="medium-correlation-value-text">80-89</span> <span class="high-correlation-value-text">90-100</span> <span class="correlation-text">Highest correlation</span>
    </div>
    <div v-if="createYourselfClicked && empty">
      <template>
        <root-node-button @click="addRootNode"></root-node-button> 
      </template>
    </div>
    <div v-if="!empty || tapestryGenerated">
      <form @submit="deleteNodes">
        <button type="submit" class="delete-submit-button">
          Delete All Nodes
        </button>
      </form>
    </div>
    <svg id="vue-svg" :viewBox="viewBox">
      <g class="links">
        <tapestry-link
          v-for="link in links"
          :key="`${link.source}-${link.target}`"
          :source="nodes[link.source]"
          :target="nodes[link.target]"
          :link="link"
        ></tapestry-link>
      </g>
      <g v-if="!dragSelectEnabled || dragSelectReady" class="nodes">
        <tapestry-node
          v-for="(node, id) in nodes"
          :key="id"
          :node="node"
          class="node"
          :class="{ selectable: true }"
          :data-id="id"
          :root="id == selectedId"
          @dragend="updateViewBox"
          @mouseover="handleMouseover(id)"
          @mouseleave="activeNode = null"
          @mounted="dragSelectEnabled ? updateSelectableNodes(node) : null"
        ></tapestry-node>
      </g>
      <locked-tooltip
        v-if="activeNode"
        :node="nodes[activeNode]"
        :viewBox="viewBox"
      ></locked-tooltip>
    </svg>
  <div>
    <div class="prompt-container" v-if="promptButtonClicked || rootNodeAdded">
      <form @submit="submitUserInput">
        <button type="submit" class="prompt-submit-button">
        </button>
        <textarea class="prompt-text-field" v-model="userInput" rows="5" cols="40" placeholder="Enter a text prompt up to 1000 words to generate a Tapestry (e.g. Machine                          learning in the workplace). Do not use the ~ character in your text."></textarea>
      </form>
    </div>
    <div class="prompt-container" v-if="promptLOButtonClicked || rootNodeAdded">
      <form @submit="submitLOUserInput">
        <button type="submit" class="prompt-submit-button">
        </button>
        <textarea class="prompt-text-field" v-model="userInput" rows="5" cols="40" placeholder="Enter a learning objective that you would like someone to learn after exploring the                Tapestry. (e.g. By the end of this Tapestry, I would like the student to have an             understanding of absence seizures.)"></textarea>
      </form>
    </div>
    <div id="loading" v-if="generatingTapestry">
      <img :src="LoadingGif" alt="Loading..."/>
    </div>
    <template>
      <div class="upload-a-pdf-drag-and-drop-zone"
        v-if="dropButtonClicked || rootNodeAdded"
        data-qa="import-file-drop"
        :class="['dropbox', { 'drag-over': isDragover }]"
        @dragenter="handleDragStart"
        @dragover="handleDragStart"
        @dragleave="handleDragEnd"
        @dragend="handleDragEnd"
        @drop="handleDragDrop"
        >
        <div class="upload-a-pdf-text-container">
          <img v-if="dragoverBackgroundColorInitial" :src="UploadPDFVector" style="width: 80px; height: 85px; margin-bottom: 23px; margin-right: 9px;"/>
          <div class="column">
            <span v-if="dragoverBackgroundColorInitial" class="upload-a-pdf-large-text">Upload a PDF</span>
            <div class="row">
              <span v-if="dragoverBackgroundColorInitial" class="upload-a-pdf-small-text">Drag and drop or</span>   
              <div>
                <input
                    ref="fileInput"
                    data-qa="import-file-input"
                    type="file"
                    style="display: none;"
                    @change="handleFileChange"
                  />
                <button v-if="(dropButtonClicked || rootNodeAdded) && dragoverBackgroundColorInitial" class="select-pdf-button" @click="openFileInput">Select PDF File</button>
              </div>
            </div>
            <br>
          </div>
        </div>
      </div>
      </template>
    </div>
    <div v-if="isDragover" class="dragover-text">Drop PDF file anywhere</div>
    <div class="container">
      <div v-if="empty && !threeButtonClicked" class="welcome-screen-text">How do you want to generate your Tapestry?</div>
      <br>
      <div class="button-container" v-if="showLearningObjectivesButton || empty && (showUploadPDF || showWritePrompt || showCreateYourself)">
        <div v-if="!showLearningObjectivesButton" class="feature-text">
          <span v-if="!showLearningObjectivesButton" class="feature-text-bold">Features with AI/Machine Learning Integration</span>
          <br>
          (automatically generate Tapestries with edit functionality)
        </div>
        <div class="buttons-flex-organization">
          <div v-if="!showLearningObjectivesButton" class="ml-button-container">
            <button class="upload-a-pdf-button" @click="uploadPDF" v-if="empty && showUploadPDF"> <img :src="UploadPDF"/> <br> <br> Upload a PDF</button>
            <button class="write-a-prompt-button" @click="nextFlow" v-if="empty && showWritePrompt"> <img :src="WritePrompt"/> <br> <br> Write a prompt</button>
          </div>
          <button class="create-it-yourself-button" @click="createYourself" v-if="empty && showCreateYourself"> <img :src="CreateYourself"/> <br> <br> Create it yourself</button>
          <button class="learning-outcomes-button" @click="writeLOPrompt" v-if="empty && showLearningObjectivesButton">
            <img :src="LearningObjectives" style="margin-bottom: 10px;"/><br><span class="white-heading-text">From Learning Objectives</span><br>
            <span class="white-text">Write a learning objective that you would like someone to learn after exploring the Tapestry. <br> (e.g. "By the end of this Tapestry, I would like the student to have an understanding of absence seizures.")</span>
          </button>
          <button class="write-a-prompt-second-button" @click="writePrompt" v-if="empty && showFromPromptButton">
            <img :src="Prompt" style="margin-bottom: 10px;"/><br><span class="white-heading-text">From a Prompt</span><br>
            <span class="white-text">Write any prompt (or copy and paste a piece of text) to generate a Tapestry from. <br> (up to 2048 characters - max input received by ChatGPT)</span>
          </button>
        </div>
      </div>
    </div>
  </main>
</template>

<script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.10.377/pdf.min.js"></script>
<script>
import DragSelectModular from "@/utils/dragSelectModular"
import { mapState, mapMutations, mapGetters, mapActions } from "vuex"
import TapestryNode from "./TapestryNode"
import TapestryLink from "./TapestryLink"
import RootNodeButton from "./RootNodeButton"
import LockedTooltip from "./LockedTooltip"
import Helpers from "@/utils/Helpers"
import { names } from "@/config/routes"
import * as wp from "@/services/wp"
import LoadingGif from "@/assets/loading.gif"
import UploadPDF from "@/assets/upload_pdf.png"
import WritePrompt from "@/assets/write_prompt.png"
import CreateYourself from "@/assets/create_yourself.png"
import Prompt from "@/assets/prompt.png"
import LearningObjectives from "@/assets/learning_objectives.png"
import { tapestryGeneration } from "./tapestryml" 
import { tapestryLOGeneration } from "./LOtapestryml"
import axios from 'axios'
import UploadPDFVector from "@/assets/upload_pdf_vector.svg"

export default {
  components: {
    TapestryNode,
    TapestryLink,
    RootNodeButton,
    LockedTooltip,
  },
  props: {
    viewBox: {
      type: String,
      required: true,
    },
  },
  data() {
    return {
      dragSelectReady: false,
      activeNode: null,
      userInput: "",
      generatingTapestry: false,
      promptButtonClicked: false,
      dropButtonClicked: false,
      createYourselfClicked: false,
      dragging: false,
      droppedFileName: '',
      threeButtonClicked: false,
      tapestryGenerated: false,
      showUploadPDF: true,
      showWritePrompt: true,
      showCreateYourself: true,
      rootNodeAdded: false,
      showLearningObjectivesButton: false,
      showFromPromptButton: false,
      promptLOButtonClicked: false,
      isDragover: false,
      dragoverBackgroundColor: "initial",
      dragoverBackgroundColorInitial: true,
      fullScreenDrop: false,
      UploadPDFVector: UploadPDFVector
    }
  },
  computed: {
    ...mapState(["nodes", "links", "selection", "settings", "rootId", "highlightedLinks"]),
    ...mapGetters(["getTheme", "getNeighbouringLinks"]),
    background() {
      return this.settings.backgroundUrl
    },
     canEdit() {
       return wp.canEditTapestry()
     },
    empty() {
      return Object.keys(this.nodes).length === 0
    },
    selectedId() {
      return Number(this.$route.params.nodeId)
    },
    dragSelectEnabled() {
      return !Helpers.isTouchEnabledDevice()
    },
    editableNodes() {
      return this.nodes.length
        ? this.nodes.filter(node => this.nodeIsEditable(node))
        : this.nodes
    },
    UploadPDF() {
      return Helpers.getImagePath(UploadPDF)
    },
    WritePrompt() {
      return Helpers.getImagePath(WritePrompt)
    },
    CreateYourself() {
      return Helpers.getImagePath(CreateYourself)
    },
    UploadPDFGray() {
      return Helpers.getImagePath(UploadPDFGray)
    },
    LoadingGif() {
      return Helpers.getImagePath(LoadingGif)
    },
    Prompt() {
      return Helpers.getImagePath(Prompt)
    },
    LearningObjectives() {
      return Helpers.getImagePath(LearningObjectives)
    }
  },
  watch: {
    background: {
      immediate: true,
      handler(background) {
        document.body.style.backgroundImage = background ? `url(${background})` : ""
      },
    },
    selectedId: {
      immediate: true,
      handler(nodeId) {
        if (this.$route.name === names.APP && !this.nodes.hasOwnProperty(nodeId)) {
          this.$router.replace(
            Object.keys(this.nodes).length === 0
              ? { path: "/", query: this.$route.query }
              : {
                  name: names.APP,
                  params: { nodeId: this.rootId },
                  query: this.$route.query,
                }
          )
        }
      },
    },
  },
  mounted() {
    if (this.dragSelectEnabled) {
      DragSelectModular.initializeDragSelect(this.$refs.app, this, this.nodes)
    }
    this.updateViewBox()
    this.dragSelectReady = true

    const tapestryGenerated = localStorage.getItem('tapestryGenerated');
  
    this.tapestryGenerated = tapestryGenerated === false;

  },
  methods: {
    ...mapMutations(["select", "unselect", "clearSelection", "setTapestryErrorReporting"]),
    ...mapActions(["deleteNode", "deleteLink"]),
    addRootNode() {
      this.$root.$emit("add-node", null)
    },

    updateSelectableNodes() {
      DragSelectModular.updateSelectableNodes()
    },
    nodeIsEditable(node) {
      return wp.isLoggedIn() && Helpers.hasPermission(node, "edit")
    },
    updateViewBox() {
      this.$parent.updateViewBox()
    },
    handleMouseover(id) {
      const node = this.nodes[id]
      if (
        !node.accessible &&
        node.nodeType !== "grandchild" &&
        node.nodeType !== ""
      ) {
        this.activeNode = id
      }
    },
    handleDragStart(evt) {
      evt.preventDefault()
      this.error = null
      this.isDragover = true
      this.dragoverBackgroundColor = "#77AEBF";
      this.dragoverBackgroundColorInitial = false;
    },
    handleDragEnd(evt) {
      evt.preventDefault()
      this.isDragover = false
      this.dragoverBackgroundColor = "initial";
      this.dragoverBackgroundColorInitial = true;
    },
    handleDragDrop(evt) {
      this.isDragover = false
      evt.preventDefault()
      evt.stopPropagation()
      const file = evt.dataTransfer.files[0]
      this.handleFile(file)
      this.fullScreenDrop = false
    },
    handleFileChange() {
      const file = this.$refs.fileInput.files[0]
      this.handleFile(file)
    },
    setTapestryGenerated(value) {
      localStorage.setItem('tapestryGenerated', value ? 'true' : 'false');
    },
    uploadPDF() {
      this.dropButtonClicked = true;
      this.promptButtonClicked = false;
      this.threeButtonClicked = true;
      this.fullScreenDrop = true;

      this.showUploadPDF = false;
      this.showWritePrompt = false;
      this.showCreateYourself = false;
    },
    writePrompt() {
      this.promptButtonClicked = true;
      this.dropButtonClicked = false;
      this.threeButtonClicked = true;

      this.showUploadPDF = false;
      this.showWritePrompt = false;
      this.showCreateYourself = false;

      this.showLearningObjectivesButton = false;
      this.showFromPromptButton = false;
    },
    writeLOPrompt() {
      this.promptButtonClicked = false;
      this.promptLOButtonClicked = true;
      this.dropButtonClicked = false;
      this.threeButtonClicked = true;

      this.showUploadPDF = false;
      this.showWritePrompt = false;
      this.showCreateYourself = false;

      this.showLearningObjectivesButton = false;
      this.showFromPromptButton = false;
    },
    createYourself() {
      this.createYourselfClicked = true;
      this.threeButtonClicked = true;
      this.promptButtonClicked = false;
      this.dropButtonClicked = false;

      this.showUploadPDF = false;
      this.showWritePrompt = false;
      this.showCreateYourself = false;
    },
    nextFlow() {
      this.promptButtonClicked = false;
      this.dropButtonClicked = false;
      this.threeButtonClicked = false;

      this.showUploadPDF = false;
      this.showWritePrompt = false;
      this.showCreateYourself = false;

      this.showLearningObjectivesButton = true;
      this.showFromPromptButton = true;
    },
    submitUserInput() {
      console.log('Submitting user input:', this.userInput);
      this.generatingTapestry = true;

      // Call the tapestryGeneration function
      tapestryGeneration(this.userInput).then(() => {
        // This code will run after the tapestryGeneration function is done

        // Hide the loading icon
        this.generatingTapestry = false;
        this.setTapestryGenerated(true);

        this.refresh();
        });
        this.showUploadPDF = false;
        this.showWritePrompt = false;
        this.showCreateYourself = false;
        this.threeButtonClicked = true;
    },
    submitLOUserInput() {
      console.log('Submitting user input:', this.userInput);
      this.generatingTapestry = true;

      tapestryLOGeneration(this.userInput).then(() => {

        this.generatingTapestry = false;
        this.setTapestryGenerated(true);

        this.refresh();
        });
        this.showUploadPDF = false;
        this.showWritePrompt = false;
        this.showCreateYourself = false;
        this.threeButtonClicked = true;
    },

    deleteEntireTapestry() {
      console.log('Deleting Entire Tapestry...');
      deleteLinks(this.userInput2);
    },

    async deleteNodes() {
      this.setTapestryErrorReporting(false)
      for (const nodeId in this.nodes) {
        if (nodeId !== this.rootId) {
          await this.deleteNode(nodeId);
          const links = this.getNeighbouringLinks(nodeId);
          console.log("Neighbouring links:", this.getNeighbouringLinks(nodeId)); 
          for(const link in links) {
            await this.deleteLink({
              source: link.source,
              target: link.target,
              useClient: false,
            })
          }
        }
      }
      await this.deleteNode(this.rootId);
      this.setTapestryGenerated(false);
      this.setTapestryErrorReporting(true);
      this.refresh();
    },
    openFileInput() {
      this.$refs.fileInput.click();
    },
    async handleFile(file) {
        if (file.type !== "application/pdf") {
          alert("Please select a PDF file.");
          return;
        }
        this.droppedFileName = file.name;

        const formData = new FormData();
        formData.append("file", file);

        try {
          const response = await axios.post('http://localhost:8000/extract-pdf-text', formData);
          const text = response.data; 
          console.log("Text extracted:", text);
          this.generatingTapestry = true;
          tapestryGeneration(text).then(() => {

            this.generatingTapestry = false;
            this.setTapestryGenerated(true);

            this.refresh(); 
          });
          this.dragging = false;
        } catch (error) {
          console.error(error);
        }
        this.showUploadPDF = false;
        this.showWritePrompt = false;
        this.showCreateYourself = false;
        this.threeButtonClicked = true; 
      },
    },
  }
</script>

<style lang="scss" scoped>
#tapestry {
  .empty-message {
    margin: 30vh auto;
  }
  svg {
    position: relative;
  }
}

.blue {
  color: #1DADE1;
}

.slider-instructions {
  position: absolute;
  background-color: #1DADE1;
  color: white;
  width: 370px;
  height: 50px;
  top: 50px;
  border-radius: 5px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: 400;
  font-size: 18px;
  right: 143px;
}

.upload-a-pdf-button {
  z-index: 3;
  height: 260px;
  width: 260px;
  background-color: #77AEBF;
  border: 2px solid #77AEBF;
  color: white;
  border-radius: 15px;
  font-size: 25px;
  margin-left: 12px;

  &:hover {
    border-width: 10px;
    border-color: #006C92;
  }
}

.write-a-prompt-button {
  z-index: 3;
  height: 260px;
  width: 260px;
  background-color: #77AEBF;
  border: 2px solid #77AEBF;
  color: white;
  border-radius: 15px;
  font-size: 25px;
  margin-left: 10px;

  &:hover {
    border-width: 10px;
    border-color: #006C92;
  }
}

.create-it-yourself-button {
  z-index: 3;
  height: 260px;
  width: 260px;
  background-color: #77AEBF;
  border: 2px solid #77AEBF;
  color: white;
  border-radius: 15px;
  font-size: 25px;
  margin-top: 19px;
  margin-left: 12px;

  &:hover {
    border-width: 10px;
    border-color: #006C92;
  }
}

.learning-outcomes-button {
  z-index: 3;
  height: 300px;
  width: 400px;
  background-color: #77AEBF;
  border: 2px solid #77AEBF;
  color: white;
  border-radius: 15px;

  &:hover {
    border-width: 10px;
    border-color: #006C92;
  }
}

.write-a-prompt-second-button {
  z-index: 3;
  height: 300px;
  width: 400px;
  background-color: #77AEBF;
  border: 2px solid #77AEBF;
  color: white;
  border-radius: 15px;

  &:hover {
    border-width: 10px;
    border-color: #006C92;
  }
}

.container {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}

.button-container {
  display: flex;
  background-color: #D9E9EF;
  justify-content: center;
  align-items: center;
  flex-direction: column;
  text-align: center;
  width: 1000px;
  height: 500px;
  border-radius: 15px;
}

.button-container button {
  margin-right: 15px;
}

.welcome-screen-text {
  z-index: 14;
  color: #006C92;
  font-weight: bold;
  font-size: 50px;
  width: 1500px;
  margin-bottom: 20px; 
}

.strength-of-relevancy-text {
  position: relative;
  height: 50px;
  width: 500px;
  background-color: white;
  border-top-left-radius: 10px;
  border-top-right-radius: 10px;
  color: #4695C2;
  font-weight: bold;
  font-size: 25px;
  align-items: center;
  text-align: center;
  margin-top: 10px;
}

.strength-of-relevancy-white-box {
  position: absolute;
  top: 115px;
  right: 143px;
  height: 210px;
  width: 570px;
  border-radius: 10px;
  background-color: white;
  color: #77AEBF;
  justify-content: center;
  font-weight: lighter;
  padding: 10px;
  }

  .navy-blue-text {
    color:#006C92;
    font-weight: bold;
  }

  .low-correlation-value-text {
    color: #77AEBF;
    font-size: 20px;
    font-weight: 1000;
    margin-right: 15px;
    margin-left: 8px;
  }

  .medium-correlation-value-text {
    color: #1DADE1;
    font-size: 20px;
    font-weight: 1000;
    margin-right: 15px;
  }

  .high-correlation-value-text {
    color: #006C92;
    font-size: 20px;
    font-weight: 1000;
    margin-right: 8px;
  }

  .correlation-text {
    color: #59595B;
    font-size: 15px;
  }
  .upload-a-pdf-text-container {
    margin-top: 350px;
    width: 600px;
    height: 300px;
    background-color: #77AEBF;
    border: dashed 7px #999999;
    display: flex;
    align-items: center;
    justify-content: center;
    position: fixed;
    top: 0%;
    left: 50%;
    transform: translate(-50%, -50%);
  }

  .upload-a-pdf-large-text {
    font-size: 57px;
    font-weight: bold;
    color: #ffffff;
  }

  .upload-a-pdf-small-text {
    font-size: 20px;
    color: #ffffff;
    margin-left: 20px;
    margin-top: 6px;
  }

  .upload-a-pdf-drag-and-drop-zone {
    position: fixed;
    top: 0;
    left: 0;
    width: 100vw;
    height: 100vh;
  }

  .ml-button-container {
    display: flex;
    width: 600px;
    height: 300px;
    border: #99C4D3 dashed;
    border-width: 10px;
    justify-content: center;
    align-items: center;
    margin-left: 15px;
  }

  .feature-text {
    margin-bottom: 20px;
    margin-left: -300px; 
    font-size: 20px;
    color: #59595B;
  }

  .feature-text-bold {
    font-weight: bolder;
    font-size: 20px;
    color: #59595B;
  }

  .buttons-flex-organization {
    display: flex;
  }

  #loading {
    position: fixed;
    top: 0;
    left: 0;
    width: 100vw;
    height: 100vh;
    background-color: rgb(255, 255, 255);
    z-index: 9999;
    display: flex;
    justify-content: center;
    align-items: center;
  }

  .dragover-text {
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    font-size: 24px;
    font-weight: bold;
    color: #333;
    z-index: 1000;
  }

  .select-pdf-button {
    position: relative;
      z-index: 1000000;
      background-color: #3289A7;
      color: white;
      border-radius: 10px;
      height: 40px;
      width: 175px;
      font-size: 20px;
      font-weight: 200;
      margin-left: 8px;
      border: 2px solid #3289A7;
      &:hover {
          border-width: 5px;
          border-color: #005a7a;
        }
  }

  .column {
    display: flex;
    flex-direction: column;
  }

  .row {
    display: flex;
    flex-direction: row;
  }

  .white-text {
    color: white;
    text-align: center;
    font-size: 13px;
    display: block;
    width: 300px;
    margin-left: auto;
    margin-right: auto;
  }

  .white-heading-text {
    color: white;
    font-size: 25px;
    margin-bottom: 10px;
  }
</style>